#everythin in reduced units as in Frenkel/Smit p.41

NUMBER_STEPS = 6*10**5 #used everywhere except MC 108
LATTICE_CONSTANT = 1.43964 #used everywhere

#MC PARAMETERS
#TEMPERATURE = 1.4275 #used in MC 108
#DJUMP = 0.2 #used in MC 108
TEMPERATURE = 1.5648 #used in MC 500
DJUMP = 0.1 #used in MC 500

#MD PARAMETERS
TIME_STEP = 0.004 #time step used in MD
EQUILIBRIUM_TIME = round(1/TIME_STEP) * 20
#TEMPERATURE = 0.728 #used in MD (mid point)
#TEMPERATURE = 0.718 #used in MD (below mid point)
#TEMPERATURE = 0.738 #used in MD (above mid point)


L = 5
NUMBER_PARTICLES = 4*(L**3)
BOX_LENGTH = L*LATTICE_CONSTANT + 0.5 * LATTICE_CONSTANT

HALF_BOX_LENGTH = BOX_LENGTH/2.
HALF_BOX_LENGTH_SQUARED = HALF_BOX_LENGTH**2
CUT_OFF_RADIUS_SQUARED = (BOX_LENGTH / 2)**2
CUT_OFF_ENERGY = 4. * ( 1./(CUT_OFF_RADIUS_SQUARED)**6 - 1./(CUT_OFF_RADIUS_SQUARED**3))

DENSITY = NUMBER_PARTICLES/BOX_LENGTH**3
BETA = 1./TEMPERATURE

